### ISSUE TITLE
[Feature request] Be able to filter by group/organization

### ISSUE THREAD

**Issue by gaeljw** [sourcebot-dev/sourcebot#141] opened 2024-12-18 14:33 UTC
It would be nice if it was possible to filter results by group (GitLab) (or organization in GitHub terminology) rather than having to check all projects belonging to the group you're interested in.

Example:
![image](https://github.com/user-attachments/assets/01d57a94-6368-43fa-8b76-7863ed7e4cd0)

It would be nice to be able to filter by group "common" or "frontend".

**Comment by KonradStanski** [comment] 2024-12-18 19:10
duplicate of: https://github.com/sourcebot-dev/sourcebot/issues/81
Agreed this would be useful, is on the agenda.

**Comment by KonradStanski** [comment] 2024-12-18 19:11
I think you can sort of achieve this in the meantime by using regex in the search path / repo.

**Comment by gaeljw** [comment] 2024-12-18 19:37
> I think you can sort of achieve this in the meantime by using regex in the search path / repo.

Ah, right! Thanks :)

**Comment by brendan-kellam** [comment] 2024-12-18 21:16
Thanks for raising - agreed with @KonradStanski, looks like #81 will fill this need. Will close this as duplicate for now.

**Closed by brendan-kellam** 2024-12-18 21:16 UTC
Labels: duplicate
